blog_front:
    resource: "@BlogFrontBundle/Resources/config/routing.yml"
    prefix:   /

eni_demo:
    resource: "@EniDemoBundle/Resources/config/routing.yml"
    prefix:   /demo

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
